import RPi.GPIO as GPIO
import time

MOTER_A1_B=6
MOTER_A1_A=5
MOTER_B1_B=21
MOTER_B1_A=20

GPIO.setmode(GPIO.BCM)
GPIO.setup(MOTER_A1_B.GPIO.OUT)
GPIO.setup(MOTER_A1_A.GPIO.OUT)
GPIO.setup(MOTER_B1_B.GPIO.OUT)
GPIO.setup(MOTER_B1_A.GPIO.OUT)


GPIO.outup(MOTER_A1_B.GPIO.[HIGH])
GPIO.outup(MOTER_A1_A.GPIO.[HIGH])
GPIO.outup(MOTER_B1_B.GPIO.[HIGH])
GPIO.outup(MOTER_B1_A.GPIO.[HIGH])